# Generated by Django 5.0.6 on 2024-05-14 19:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
