# Generated by Django 5.0.6 on 2024-05-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0007_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
