# Generated by Django 5.0.6 on 2024-05-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0008_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
